services:
  - type: web
    plan: free
    name: origik
    runtime: docker
    repo: https://github.com/jpruden92/origik.git
    branch: main
    rootDir: .
    region: frankfurt
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RARIBLE_API_URL
        value: https://testnet-api.rarible.org/v0.1
      - key: COLLECTION_NAME
        value: Origik
      - key: COLLECTION_NETWORK
        value: ETHEREUM
      - key: RARIBLE_API_KEY
        sync: false
      - key: INFURA_KEY
        sync: false

databases:
  - name: postgres
    plan: free
    region: frankfurt